openapi: 3.0.0
info:
  title: Employee Service API
  description: API documentation for managing employees
  version: "1.0.0"

paths:
  /employees:
    get:
      summary: Get all employees
      tags:
        - Employees
      responses:
        '200':
          description: List of employees
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/Employee'

    post:
      summary: Create a new employee
      tags:
        - Employees
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeInput'
      responses:
        '201':
          description: Employee created
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                  payload:
                    $ref: '#/components/schemas/Employee'

  /employees/{id}:
    get:
      summary: Get employee by ID
      tags:
        - Employees
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Employee found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                  payload:
                    $ref: '#/components/schemas/Employee'

    put:
      summary: Update employee by ID
      tags:
        - Employees
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeInput'
      responses:
        '200':
          description: Employee updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                  payload:
                    $ref: '#/components/schemas/Employee'

    delete:
      summary: Delete employee by ID
      tags:
        - Employees
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Employee deleted

components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
    EmployeeInput:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
