openapi: 3.0.0
info:
  title: Auth Service API
  description: API documentation for the authentication service
  version: "1.0.0"

paths:
  /login:
    post:
      summary: Log in a user and receive a JWT token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: admin123
      responses:
        '200':
          description: JWT token returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  payload:
                    type: string
                    description: JWT token
